Description: >
  Udagram Web App IAM Roles Assignment
Parameters:
  EnvironmentName:
    Description: Environment name that will be prefixed to our resource variables
    Type: String

Resources:
  IAMRoleWebApp:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  IAMWebAppS3IP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRoleWebApp"

Outputs:
  IAMRoleWebApp:
    Description: "Allow EC2 instances to manage deployed app's S3 bucket"
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${EnvironmentName}-IAM
  IAMRoleWebAppArn:
    Description: IAM Instance Profile Arn
    Value: !GetAtt IAMRoleWebApp.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN